.This code makes no sense, it is just for testing purpose.
SUM		START	8000
FIRST	LDX		ZERO		INITIALIZE REGISTERS
		LDA		ZERO
LOOP	ADD		TABLE,X		ADD THE ELEMENTS
		TIX		COUNT		ARE WE DONE?
LOOP	JT		LOOP		IF NOT, LOOP
		STA		TOTAL		STORE THE TOTAL
		RSUB				AND RETURN
8TABLE	RESW	2000		FOR THE ARRAY
COUN.T	RESW				NUMBER OF ELEMENTS
		ADD		Count-X
INPUT   BYTE    X'F41'		CODE FOR INPUT DEVICE
BUFFER  RESB    4096		4096-BYTE BUFFER AREA
EOF     BYTE    S'EOF'
ZERO	WORD	A			CONSTANT
OUTPUT  BYTE   	X'G5'		CODE FOR OUTPUT DEVICE
TOTAL	RESW	1			PLACE FOR TOTAL
		END		